require('config');
require('log');
require('fizlib');
require('garbage_collector');
require('prototype_creep');
require('prototype_room');
require('prototype_roomposition');
require('prototype_structure');
require('role');